// // https://www.youtube.com/watch?v=PSyJqt6wCIY
// console.log('texto ... numero');
// let numero: number = 15;
// let texto: string = '15';
// let numeroStringAmpla: boolean = texto == numero;
// console.log(numeroStringAmpla);
// let numeroStringEstrita: boolean = texto === numero;
// console.log(numeroStringEstrita);
// console.log(typeof (texto));
// console.log(typeof (numero));
// console.log("'15' ... 15");
// let numeroStringAmpla2: boolean = '15' == 15;
// console.log(numeroStringAmpla2);
// let numeroStringEstrita2: boolean = '15' === 15;
// console.log(numeroStringEstrita2);
// console.log(typeof ('15'));
// console.log(typeof (15));
// console.log('0 ... false');
// let numeroStringAmpla3: boolean = 0 == false;
// console.log(numeroStringAmpla3);
// let numeroStringEstrita3: boolean = 0 === false;
// console.log(numeroStringEstrita3);
// console.log(typeof (0));
// console.log(typeof (false));
// console.log('undefined ... null');
// let numeroStringAmpla4: boolean = undefined == null;
// console.log(numeroStringAmpla4);
// let numeroStringEstrita4: boolean = undefined === null;
// console.log(numeroStringEstrita4);
// console.log(typeof (undefined));
// console.log(typeof (null));
// console.log('0 ... null');
// let numeroStringAmpla5: boolean = 0 == null;
// console.log(numeroStringAmpla5);
// let numeroStringEstrita5: boolean = 0 === null;
// console.log(numeroStringEstrita5);
// console.log(typeof (0));
// console.log(typeof (null));
// let saldo = 0;
// if (saldo) {
//     console.log('saldo == 0');
// } else {
//     console.log('saldo != 0');
// }
// console.log('\t\n ... false');
// let numeroStringAmpla6: boolean = '\t\n' == false;
// console.log(numeroStringAmpla6);
// let numeroStringEstrita6: boolean = '\t\n' === false;
// console.log(numeroStringEstrita6);
// console.log(typeof ('\t\n'));
// console.log(typeof (false));
// console.log("'' ... false");
// let numeroStringAmpla7: boolean = '' == false;
// console.log(numeroStringAmpla7);
// let numeroStringEstrita7: boolean = '' === false;
// console.log(numeroStringEstrita7);
// console.log(typeof (''));
// console.log(typeof (false));
// console.log("'0' ... new String('0')");
// let numeroStringAmpla8: boolean = '0' == new String('0');
// console.log(numeroStringAmpla8);
// let numeroStringEstrita8: boolean = '0' === new String('0');
// console.log(numeroStringEstrita8);
// console.log(typeof ('0'));
// console.log(typeof (new String('0')));
//# sourceMappingURL=igualdade.js.map